package cli

import (
	"fmt"
	"io"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

// genNushellCompletion writes a Nushell completion script for the given command tree to w.
func genNushellCompletion(root *cobra.Command, w io.Writer) {
	fmt.Fprintf(w, "# Generated by %s completion nushell\n\n", root.Name())
	writeNushellExtern(root, root.Name(), w)
	for _, sub := range root.Commands() {
		writeNushellExtern(sub, root.Name()+" "+sub.Name(), w)
	}
}

func writeNushellExtern(cmd *cobra.Command, name string, w io.Writer) {
	fmt.Fprintf(w, "extern \"%s\" [\n", name)
	cmd.Flags().VisitAll(func(f *pflag.Flag) {
		if f.Hidden {
			return
		}
		flag := "  --" + f.Name
		if f.Shorthand != "" {
			flag += "(-" + f.Shorthand + ")"
		}
		if nuType := nushellFlagType(f.Value.Type()); nuType != "" {
			flag += ": " + nuType
		}
		fmt.Fprintf(w, "%s\t# %s\n", flag, f.Usage)
	})
	fmt.Fprintf(w, "  --help(-h)\t# Show help for %s\n", cmd.Name())
	fmt.Fprintf(w, "]\n\n")
}

// nushellFlagType maps a pflag type name to its Nushell type annotation.
// Returns "" for bool flags (no annotation needed in Nushell).
func nushellFlagType(pflagType string) string {
	switch pflagType {
	case "bool":
		return ""
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64",
		"count":
		return "int"
	case "float32", "float64":
		return "number"
	default:
		return "string"
	}
}
